# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: wx59536.eu-west-3.aws
      
      # User/password auth
      user: ABERNAL
      password: L3talBern4l

      role: ACCOUNTADMIN
      database: RAW
      warehouse: TRANSFORMING
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False
      query_tag: DBT_TEST

      # optional
      connect_retries: 1 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: false 
      retry_all: True  # default: false